
package com.example.wsdl.com.soap_app;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ConverterPort", targetNamespace = "http://www.soap-app.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConverterPort {


    /**
     * 
     * @param convertedXmlRequest
     * @return
     *     returns com.soap_app.ConvertedXmlResponse
     */
    @WebMethod
    @WebResult(name = "convertedXmlResponse", targetNamespace = "http://www.soap-app.com/", partName = "convertedXmlResponse")
    public ConvertedXmlResponse convertedXml(
        @WebParam(name = "convertedXmlRequest", targetNamespace = "http://www.soap-app.com/", partName = "convertedXmlRequest")
        ConvertedXmlRequest convertedXmlRequest);

}
