
package com.example.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConverterPortService", targetNamespace = "http://www.soap-app.com/", wsdlLocation = "http://localhost:8081/service/converterWsdl.wsdl")
public class ConverterPortService
    extends Service
{

    private static final URL CONVERTERPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException CONVERTERPORTSERVICE_EXCEPTION;
    private static final QName CONVERTERPORTSERVICE_QNAME = new QName("http://www.soap-app.com/", "ConverterPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/service/converterWsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTERPORTSERVICE_WSDL_LOCATION = url;
        CONVERTERPORTSERVICE_EXCEPTION = e;
    }

    public ConverterPortService() {
        super(__getWsdlLocation(), CONVERTERPORTSERVICE_QNAME);
    }

    public ConverterPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTERPORTSERVICE_QNAME, features);
    }

    public ConverterPortService(URL wsdlLocation) {
        super(wsdlLocation, CONVERTERPORTSERVICE_QNAME);
    }

    public ConverterPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTERPORTSERVICE_QNAME, features);
    }

    public ConverterPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConverterPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConverterPort
     */
    @WebEndpoint(name = "ConverterPortSoap11")
    public ConverterPort getConverterPortSoap11() {
        return super.getPort(new QName("http://www.soap-app.com/", "ConverterPortSoap11"), ConverterPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConverterPort
     */
    @WebEndpoint(name = "ConverterPortSoap11")
    public ConverterPort getConverterPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.soap-app.com/", "ConverterPortSoap11"), ConverterPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTERPORTSERVICE_EXCEPTION!= null) {
            throw CONVERTERPORTSERVICE_EXCEPTION;
        }
        return CONVERTERPORTSERVICE_WSDL_LOCATION;
    }

}
