create database work_test_task;

drop table if exists document;
drop table if exists person;

create table person
(
    id         int generated by default as identity primary key,
    name       varchar(50) not null,
    surname    varchar(50) not null,
    patronymic varchar(50) not null,
    birth_date  date        not null,
    gender     varchar(5)  not null
);

create table document
(
    person_id  int references person on delete cascade primary key ,
    series     int         not null,
    number     int         not null,
    type       varchar(25) not null,
    issue_date date        not null,
);
